### PR TITLE
Create miaconcept1.png

### LINKED ISSUE #1: Mia Character Design
# Mia - Main Girl
## Physical Description
Mia has straight Black Hair that she ties in a ponytail that extends down to just below the shoulder blades in the back and falls to just above her shoulder in the front. She is 5'10'' and her left hand and arm is severely scarred  by lacerations which although they are mostly not visible stand in stark contrast to her pale complexion.  She has distinct eyelashes that, while not to thick, are prominent both at the the top of the eye and the bottom. She has a very kind warm expression and gives off a welcoming feeling. She wears wears a jacket and pants most of the time both of which are usually dark in color. She wears combat boots and occasionally a scarf but is never seen without a simple small silver hair pin in her hair. Additionally, her eyes are Amber

## Reference Characters
- Pham Thi Lan from Schwarzesmarken.
- Touka Takanashi in terms of figure from chuunibyo demo koi ga shitai.

## Points of contact for more info
- @cherisu
- @Avuxo

### PR DESCRIPTION
**Pull request by hsuch**
resolve #1

### CODE REVIEW

**Comment by Avuxo** [comment]
I knew you were good from the stuff I'd seen before, but this looks absolutely god damn incredible. The fact you did this in only like 4 hours just blows me away.

## Some notes
For her hair, I think the center design or the rightmost is probably our best bet. Chris is free to weigh in, but I'm on team right-side hair. Monika-style is good, but there's no hairpin and her hair is straight.

When I suggested Adidas, I meant the jacket : / Although the sneakers look really good, I think she's better off wearing boots if she's in the middle of a warzone. I want those three stripes though (for copyright reasons, please only use 2 :pensive:).

Whatever spell you placed on the image on the right side in the vertical center, I need more of that. I'm in love with her.

Seriously, if this is just the concept work you can do (and so rapidly), I am _excited_ for the next design. Phenomenal work, honestly.

**Review by Avuxo — APPROVED** [review]
lgtm

**Review by ghost — APPROVED** [review]
I think that this looks amazing and I am really happy with the way you portrayed her. My favorite hair style is probably the third one followed fairly closely by the first one. I think that I would like to keep the hair pin as it holds some importance to the story and I think that either eye color would be fine although I leaning towards the more yellow eye color. I really like the second and third jacket designs but in the third outfit I feel as thought the stripes on her shirt are a little out of place and she looks like she is wearing her pants a little to high up on her body. It looks really damn good though.

**Comment by hsuch** [comment]
Thanks y'all. Your comments flatter me :cry: 
I like the third style the most too. I think I'll go with that. It has a nice look when it's all straight.
Sorry about the jacket, whenever I think of adidas I think of sneakers
The speed will probably be the exception and not the norm, I just happened to have time today. :stuck_out_tongue_closed_eyes: 

The high waisted pants are a 90s style and they're to my personal taste. Cropped sweater and high waisted cuffed jeans are justice. (They're also in fashion now but...)
I was trying to stick to a 90s textile look with the stripes, but we can get rid of them. I just figured they would show up on a sprite even with low fidelity, but I think we already have the scarf as a point of interest as well.

**Pull request merged**
